# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20150110082547) do

  create_table "accidents", :force => true do |t|
    t.date     "injury_date"
    t.text     "injury_description"
    t.string   "accident_type"
    t.boolean  "wearing_seat_belt"
    t.boolean  "pedestrian"
    t.boolean  "driver"
    t.boolean  "passenger"
    t.string   "seating_position"
    t.boolean  "airbag_deploy"
    t.boolean  "loss_of_consciousness"
    t.boolean  "lost_time_from_work"
    t.boolean  "taken_to_hospital"
    t.string   "hospital_name"
    t.string   "hospital_transport_mode"
    t.boolean  "examined"
    t.boolean  "xrays"
    t.boolean  "ctscan"
    t.boolean  "mri"
    t.boolean  "released"
    t.boolean  "admitted"
    t.text     "medications"
    t.text     "prior_injuries"
    t.string   "prior_diagnostic_study_mri"
    t.string   "prior_diagnostic_study_mri_other"
    t.string   "prior_diagnostic_study_ctscan"
    t.string   "prior_diagnostic_study_ctscan_other"
    t.string   "prior_diagnostic_study_emg"
    t.text     "prior_diagnostic_results"
    t.text     "medical_history"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "patient_id"
    t.string   "days_lost_from_work"
    t.boolean  "fear_while_driving"
  end

  create_table "chiropractic_assessments", :force => true do |t|
    t.boolean  "assessment_improved"
    t.boolean  "assessment_unimproved"
    t.boolean  "assessment_exacerbation"
    t.text     "updated_diagnosis"
    t.text     "comments"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_examination_id"
  end

  create_table "chiropractic_body_adjustment_lists", :force => true do |t|
    t.boolean  "spinal_adjustment_1_2_regions"
    t.boolean  "spinal_adjustment_3_4_regions"
    t.boolean  "spinal_adjustment_5_or_more_regions"
    t.boolean  "extremity_adjustment_shoulder_left"
    t.boolean  "extremity_adjustment_shoulder_right"
    t.boolean  "extremity_adjustment_elbow_left"
    t.boolean  "extremity_adjustment_elbow_right"
    t.boolean  "extremity_adjustment_wrist_left"
    t.boolean  "extremity_adjustment_wrist_right"
    t.boolean  "extremity_adjustment_hip_left"
    t.boolean  "extremity_adjustment_hip_right"
    t.boolean  "extremity_adjustment_knee_left"
    t.boolean  "extremity_adjustment_knee_right"
    t.boolean  "extremity_adjustment_ankle_left"
    t.boolean  "extremity_adjustment_ankle_right"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_treatment_id"
    t.boolean  "cmt_cervical"
    t.boolean  "cmt_thoracic"
    t.boolean  "cmt_lumbar"
    t.boolean  "cmt_hip"
    t.boolean  "cmt_pelvis"
    t.boolean  "cmt_shoulder"
    t.boolean  "cmt_elbow"
    t.boolean  "cmt_hand"
    t.boolean  "cmt_knee"
    t.boolean  "cmt_ankle"
    t.boolean  "cmt_sacrum"
    t.boolean  "subluxation_c1"
    t.boolean  "subluxation_c2"
    t.boolean  "subluxation_c3"
    t.boolean  "subluxation_c4"
    t.boolean  "subluxation_c5"
    t.boolean  "subluxation_c6"
    t.boolean  "subluxation_c7"
    t.boolean  "subluxation_t1"
    t.boolean  "subluxation_t2"
    t.boolean  "subluxation_t3"
    t.boolean  "subluxation_t4"
    t.boolean  "subluxation_t5"
    t.boolean  "subluxation_t6"
    t.boolean  "subluxation_t7"
    t.boolean  "subluxation_t8"
    t.boolean  "subluxation_t9"
    t.boolean  "subluxation_t10"
    t.boolean  "subluxation_t11"
    t.boolean  "subluxation_t12"
    t.boolean  "subluxation_l1"
    t.boolean  "subluxation_l2"
    t.boolean  "subluxation_l3"
    t.boolean  "subluxation_l4"
    t.boolean  "subluxation_l5"
  end

  create_table "chiropractic_compliances", :force => true do |t|
    t.string   "compliance"
    t.boolean  "compliance_affected_by_transportation"
    t.boolean  "compliance_affected_by_work_schedule"
    t.boolean  "compliance_affected_by_personal_matter"
    t.string   "other_reason_for_compliance"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_examination_id"
  end

  create_table "chiropractic_diagnosis_lists", :force => true do |t|
    t.boolean  "cervical_sprain"
    t.boolean  "cervical_radiculopathy"
    t.boolean  "cervicalgia"
    t.boolean  "segmental_dysfunction_c"
    t.boolean  "cervical_disc_herniation"
    t.boolean  "cervical_myelopathy"
    t.boolean  "thoracic_myelopathy"
    t.boolean  "thoracic_sprain"
    t.boolean  "thoracic_pain"
    t.boolean  "segmental_dysfunction_t"
    t.boolean  "scoliosis"
    t.boolean  "sciatica"
    t.boolean  "lumbar_sprain"
    t.boolean  "lumbar_radiculopathy"
    t.boolean  "lumbago"
    t.boolean  "lumbar_disc_herniation"
    t.boolean  "lumbar_myelopathy"
    t.boolean  "sacroiliac_sprain"
    t.boolean  "paresthesia"
    t.boolean  "segmental_dysfunction_l"
    t.boolean  "myofascitis"
    t.boolean  "shoulder_sprain_left"
    t.boolean  "shoulder_sprain_right"
    t.boolean  "shoulder_dysfunction_left"
    t.boolean  "shoulder_dysfunction_right"
    t.boolean  "elbow_sprain_left"
    t.boolean  "elbow_sprain_right"
    t.boolean  "wrist_sprain_left"
    t.boolean  "wrist_sprain_right"
    t.boolean  "cervical_trigger_point"
    t.boolean  "lumbar_trigger_point"
    t.boolean  "hip_sprain_left"
    t.boolean  "hip_sprain_right"
    t.boolean  "hip_dysfunction_left"
    t.boolean  "hip_dysfunction_right"
    t.boolean  "knee_sprain_left"
    t.boolean  "knee_sprain_right"
    t.boolean  "ankle_sprain_left"
    t.boolean  "ankle_sprain_right"
    t.boolean  "headaches"
    t.boolean  "dizziness"
    t.boolean  "post_concussive_syndrome"
    t.string   "other_diagnosis"
    t.string   "other_diagnosis_code"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_examination_id"
    t.boolean  "sacral_segmental_dysfunction"
  end

  create_table "chiropractic_examinations", :force => true do |t|
    t.date     "examination_date"
    t.string   "current_step",             :default => "chiropractic_symptom_list"
    t.boolean  "completed",                :default => false
    t.datetime "completed_at"
    t.integer  "completed_by"
    t.boolean  "insurance_claim_filed",    :default => false
    t.datetime "insurance_claim_filed_at"
    t.integer  "insurance_claim_filed_by"
    t.boolean  "initial_examination"
    t.boolean  "duration_20_minutes"
    t.boolean  "duration_30_minutes"
    t.boolean  "duration_45_minutes"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.boolean  "email_sent",               :default => false
    t.integer  "accident_id"
    t.integer  "client_id"
    t.string   "summary"
  end

  create_table "chiropractic_investigation_lists", :force => true do |t|
    t.boolean  "ecohymosis"
    t.boolean  "lacerations"
    t.boolean  "edema"
    t.string   "exam_notes"
    t.string   "systolic_blood_pressure"
    t.string   "diastolic_blood_pressure"
    t.string   "pulse"
    t.boolean  "cranial_nerves_grossly_intact"
    t.boolean  "cranial_nerves_abnormal"
    t.string   "cranial_nerves_abnormality"
    t.string   "crom_flex_exam"
    t.boolean  "crom_flex_pain"
    t.boolean  "crom_flex_discomfort"
    t.string   "lrom_flex_exam"
    t.boolean  "lrom_flex_pain"
    t.boolean  "lrom_flex_discomfort"
    t.string   "crom_ext_exam"
    t.boolean  "crom_ext_pain"
    t.boolean  "crom_ext_discomfort"
    t.string   "lrom_ext_exam"
    t.boolean  "lrom_ext_pain"
    t.boolean  "lrom_ext_discomfort"
    t.string   "crom_lrot_exam"
    t.boolean  "crom_lrot_pain"
    t.boolean  "crom_lrot_discomfort"
    t.string   "lrom_lrot_exam"
    t.boolean  "lrom_lrot_pain"
    t.boolean  "lrom_lrot_discomfort"
    t.string   "crom_rrot_exam"
    t.boolean  "crom_rrot_pain"
    t.boolean  "crom_rrot_discomfort"
    t.string   "lrom_rrot_exam"
    t.boolean  "lrom_rrot_pain"
    t.boolean  "lrom_rrot_discomfort"
    t.string   "crom_llf_exam"
    t.boolean  "crom_llf_pain"
    t.boolean  "crom_llf_discomfort"
    t.string   "lrom_llf_exam"
    t.boolean  "lrom_llf_pain"
    t.boolean  "lrom_llf_discomfort"
    t.string   "crom_rlf_exam"
    t.boolean  "crom_rlf_pain"
    t.boolean  "crom_rlf_discomfort"
    t.string   "lrom_rlf_exam"
    t.boolean  "lrom_rlf_pain"
    t.boolean  "lrom_rlf_discomfort"
    t.text     "other_roms"
    t.boolean  "cervical_paraspinal_musculature_noted"
    t.string   "cervical_paraspinal_musculature_side"
    t.boolean  "throacic_paraspinal_musculature_noted"
    t.string   "throacic_paraspinal_musculature_side"
    t.boolean  "lumbar_paraspinal_musculature_noted"
    t.string   "lumbar_paraspinal_musculature_side"
    t.boolean  "motor_testing"
    t.text     "motor_testing_exception"
    t.boolean  "subluxation_c1"
    t.boolean  "subluxation_c2"
    t.boolean  "subluxation_c3"
    t.boolean  "subluxation_c4"
    t.boolean  "subluxation_c5"
    t.boolean  "subluxation_c6"
    t.boolean  "subluxation_c7"
    t.boolean  "subluxation_t1"
    t.boolean  "subluxation_t2"
    t.boolean  "subluxation_t3"
    t.boolean  "subluxation_t4"
    t.boolean  "subluxation_t5"
    t.boolean  "subluxation_t6"
    t.boolean  "subluxation_t7"
    t.boolean  "subluxation_t8"
    t.boolean  "subluxation_t9"
    t.boolean  "subluxation_t10"
    t.boolean  "subluxation_t11"
    t.boolean  "subluxation_t12"
    t.boolean  "subluxation_l1"
    t.boolean  "subluxation_l2"
    t.boolean  "subluxation_l3"
    t.boolean  "subluxation_l4"
    t.boolean  "subluxation_l5"
    t.boolean  "dermatomes"
    t.text     "dermatomes_exception"
    t.string   "dtr_biceps_right"
    t.string   "dtr_biceps_left"
    t.string   "dtr_pronator_right"
    t.string   "dtr_pronator_left"
    t.string   "dtr_triceps_right"
    t.string   "dtr_triceps_left"
    t.string   "dtr_patella_right"
    t.string   "dtr_patella_left"
    t.string   "dtr_achilles_right"
    t.string   "dtr_achilles_left"
    t.boolean  "orthopedic_test_cervical_comp_right"
    t.boolean  "orthopedic_test_cervical_comp_left"
    t.boolean  "orthopedic_test_distraction_right"
    t.boolean  "orthopedic_test_distraction_left"
    t.boolean  "orthopedic_test_shoulder_dep_right"
    t.boolean  "orthopedic_test_shoulder_dep_left"
    t.boolean  "orthopedic_test_soto_hall_right"
    t.boolean  "orthopedic_test_soto_hall_left"
    t.boolean  "orthopedic_test_slr_right"
    t.boolean  "orthopedic_test_slr_left"
    t.boolean  "orthopedic_test_braggard_right"
    t.boolean  "orthopedic_test_braggard_left"
    t.boolean  "orthopedic_test_kemps_right"
    t.boolean  "orthopedic_test_kemps_left"
    t.boolean  "orthopedic_test_valsalva_right"
    t.boolean  "orthopedic_test_valsalva_left"
    t.boolean  "orthopedic_test_nachlas_right"
    t.boolean  "orthopedic_test_nachlas_left"
    t.boolean  "orthopedic_test_yeomans_right"
    t.boolean  "orthopedic_test_yeomans_left"
    t.boolean  "orthopedic_test_fabere_patrick_right"
    t.boolean  "orthopedic_test_fabere_patrick_left"
    t.boolean  "orthopedic_test_elys_right"
    t.boolean  "orthopedic_test_elys_left"
    t.boolean  "orthopedic_test_georges_right"
    t.boolean  "orthopedic_test_georges_left"
    t.boolean  "orthopedic_test_squat_right"
    t.boolean  "orthopedic_test_squat_left"
    t.boolean  "orthopedic_test_spurlings_right"
    t.boolean  "orthopedic_test_spurlings_left"
    t.boolean  "orthopedic_test_supraspinatus_right"
    t.boolean  "orthopedic_test_supraspinatus_left"
    t.boolean  "orthopedic_test_minors_sign_right"
    t.boolean  "orthopedic_test_minors_sign_left"
    t.boolean  "orthopedic_test_trendelenberg_right"
    t.boolean  "orthopedic_test_trendelenberg_left"
    t.boolean  "orthopedic_test_jackson_right"
    t.boolean  "orthopedic_test_jackson_left"
    t.string   "orthopedic_test_other"
    t.string   "grip_strength_dyn1_right"
    t.string   "rip_strength_dyn1_left"
    t.string   "grip_strength_dyn2_right"
    t.string   "rip_strength_dyn2_left"
    t.string   "grip_strength_dyn3_right"
    t.string   "rip_strength_dyn3_left"
    t.boolean  "standing_activity_affected"
    t.boolean  "sitting_activity_affected"
    t.boolean  "bending_activity_affected"
    t.boolean  "lifting_activity_affected"
    t.boolean  "walking_activity_affected"
    t.boolean  "sleeping_activity_affected"
    t.string   "other_activities_affected"
    t.text     "orthopedic_neuro_tests"
    t.text     "other_diagnostic_tests"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_examination_id"
    t.boolean  "show_cervical_comp"
    t.boolean  "show_distraction"
    t.boolean  "show_shoulder_dep"
    t.boolean  "show_soto_hall"
    t.boolean  "show_slr"
    t.boolean  "show_braggard"
    t.boolean  "show_kemps"
    t.boolean  "show_valsalva"
    t.boolean  "show_nachlas"
    t.boolean  "show_yeomans"
    t.boolean  "show_fabere_patrick"
    t.boolean  "show_elys"
    t.boolean  "show_georges"
    t.boolean  "show_squat"
    t.boolean  "show_spurlings"
    t.boolean  "show_supraspinatus"
    t.boolean  "show_minors_sign"
    t.boolean  "show_trendelenberg"
    t.boolean  "show_jackson"
    t.string   "srom_flex_right_exam"
    t.string   "srom_flex_left_exam"
    t.boolean  "srom_flex_pain"
    t.boolean  "srom_flex_discomfort"
    t.string   "srom_ext_right_exam"
    t.string   "srom_ext_left_exam"
    t.boolean  "srom_ext_pain"
    t.boolean  "srom_ext_discomfort"
    t.string   "srom_int_rot_right_exam"
    t.string   "srom_int_rot_left_exam"
    t.boolean  "srom_int_rot_pain"
    t.boolean  "srom_int_rot_discomfort"
    t.string   "srom_ext_rot_right_exam"
    t.string   "srom_ext_rot_left_exam"
    t.boolean  "srom_ext_rot_pain"
    t.boolean  "srom_ext_rot_discomfort"
    t.string   "srom_adduction_right_exam"
    t.string   "srom_adduction_left_exam"
    t.boolean  "srom_adduction_pain"
    t.boolean  "srom_adduction_discomfort"
    t.string   "srom_abduction_right_exam"
    t.string   "srom_abduction_left_exam"
    t.boolean  "srom_abduction_pain"
    t.boolean  "srom_abduction_discomfort"
    t.string   "hrom_flex_right_exam"
    t.string   "hrom_flex_left_exam"
    t.boolean  "hrom_flex_pain"
    t.boolean  "hrom_flex_discomfort"
    t.string   "hrom_ext_right_exam"
    t.string   "hrom_ext_left_exam"
    t.boolean  "hrom_ext_pain"
    t.boolean  "hrom_ext_discomfort"
    t.string   "hrom_int_rot_right_exam"
    t.string   "hrom_int_rot_left_exam"
    t.boolean  "hrom_int_rot_pain"
    t.boolean  "hrom_int_rot_discomfort"
    t.string   "hrom_ext_rot_right_exam"
    t.string   "hrom_ext_rot_left_exam"
    t.boolean  "hrom_ext_rot_pain"
    t.boolean  "hrom_ext_rot_discomfort"
    t.string   "hrom_adduction_right_exam"
    t.string   "hrom_adduction_left_exam"
    t.boolean  "hrom_adduction_pain"
    t.boolean  "hrom_adduction_discomfort"
    t.string   "hrom_abduction_right_exam"
    t.string   "hrom_abduction_left_exam"
    t.boolean  "hrom_abduction_pain"
    t.boolean  "hrom_abduction_discomfort"
    t.string   "krom_flex_right_exam"
    t.string   "krom_flex_left_exam"
    t.boolean  "krom_flex_pain"
    t.boolean  "krom_flex_discomfort"
    t.string   "krom_ext_right_exam"
    t.string   "krom_ext_left_exam"
    t.boolean  "krom_ext_pain"
    t.boolean  "krom_ext_discomfort"
    t.string   "krom_int_rot_right_exam"
    t.string   "krom_int_rot_left_exam"
    t.boolean  "krom_int_rot_pain"
    t.boolean  "krom_int_rot_discomfort"
    t.string   "krom_ext_rot_right_exam"
    t.string   "krom_ext_rot_left_exam"
    t.boolean  "krom_ext_rot_pain"
    t.boolean  "krom_ext_rot_discomfort"
    t.string   "krom_adduction_right_exam"
    t.string   "krom_adduction_left_exam"
    t.boolean  "krom_adduction_pain"
    t.boolean  "krom_adduction_discomfort"
    t.string   "krom_abduction_right_exam"
    t.string   "krom_abduction_left_exam"
    t.boolean  "krom_abduction_pain"
    t.boolean  "krom_abduction_discomfort"
  end

  create_table "chiropractic_modalities_lists", :force => true do |t|
    t.boolean  "ultrasound"
    t.boolean  "electric_stimulation"
    t.boolean  "moist_heat"
    t.boolean  "massage"
    t.boolean  "mfr_cervical"
    t.boolean  "mfr_thoracic"
    t.boolean  "mfr_lumbar"
    t.boolean  "therapeutic_exercise"
    t.boolean  "mechanical_traction"
    t.boolean  "kinetic_activity"
    t.boolean  "nmr"
    t.boolean  "gait_training"
    t.boolean  "exam_re_exam"
    t.boolean  "home_use_instruction"
    t.string   "other"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_treatment_id"
    t.boolean  "infrared"
    t.boolean  "hot_cold_pack"
    t.boolean  "bio_feedback"
    t.boolean  "therapeutic_functional_activities"
    t.boolean  "supplies_bio_freeze"
    t.boolean  "supplies_ice_pack"
    t.boolean  "supplies_lumbar_belt"
    t.boolean  "supplies_cervical_pillow"
    t.boolean  "supplies_cervical_collar"
  end

  create_table "chiropractic_observation_lists", :force => true do |t|
    t.boolean  "myospasms"
    t.boolean  "tenderness"
    t.boolean  "hypotonicity"
    t.boolean  "flare_ups"
    t.boolean  "suboccipitals"
    t.boolean  "rhomboids"
    t.boolean  "deltoids"
    t.boolean  "quad_lumb"
    t.boolean  "uppertraps"
    t.boolean  "levator_scap"
    t.boolean  "ctl_paraspinals"
    t.string   "other_observations"
    t.boolean  "disc_c1"
    t.boolean  "disc_c2"
    t.boolean  "disc_c3"
    t.boolean  "disc_c4"
    t.boolean  "disc_c5"
    t.boolean  "disc_c6"
    t.boolean  "disc_c7"
    t.boolean  "disc_t1"
    t.boolean  "disc_t2"
    t.boolean  "disc_t3"
    t.boolean  "disc_t4"
    t.boolean  "disc_t5"
    t.boolean  "disc_t6"
    t.boolean  "disc_t7"
    t.boolean  "disc_t8"
    t.boolean  "disc_t9"
    t.boolean  "disc_t10"
    t.boolean  "disc_t11"
    t.boolean  "disc_t12"
    t.boolean  "disc_l1"
    t.boolean  "disc_l2"
    t.boolean  "disc_l3"
    t.boolean  "disc_l4"
    t.boolean  "disc_l5"
    t.boolean  "occiput"
    t.boolean  "sacrum"
    t.boolean  "sacroiliac_left"
    t.boolean  "sacroiliac_right"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_treatment_id"
    t.boolean  "symptom_headache"
    t.boolean  "symptom_neck_pain"
    t.boolean  "symptom_upper_back_pain"
    t.boolean  "symptom_mid_back_pain"
    t.boolean  "symptom_low_back_pain"
    t.boolean  "symptom_pelvis_pain"
    t.boolean  "symptom_hip_pain"
    t.boolean  "symptom_knee_pain"
    t.boolean  "symptom_ankle_pain"
    t.boolean  "symptom_shoulder_pain"
    t.boolean  "symptom_elbow_pain"
    t.boolean  "symptom_wrist_pain"
    t.string   "symptom_other_pain"
    t.boolean  "muscle_spasm_cervical"
    t.boolean  "muscle_spasm_thoracic"
    t.boolean  "muscle_spasm_lumbar"
    t.boolean  "muscle_spasm_hip"
    t.boolean  "muscle_spasm_shoulder"
    t.boolean  "muscle_spasm_upper_extremity"
    t.boolean  "muscle_spasm_lower_extremity"
    t.boolean  "findings_increased_muscle_spasm"
    t.boolean  "findings_increased_apprehension"
    t.boolean  "findings_biomechanical_dysfunction"
    t.boolean  "findings_upper_trapezius_spasm"
    t.boolean  "findings_fibrous_tissue_adhesions"
    t.boolean  "findings_activator_technique_used"
    t.boolean  "findings_sub_optimal_response"
    t.boolean  "findings_life_style_affected_by_pain"
    t.boolean  "findings_involuntary_contractions"
    t.string   "findings_other"
    t.integer  "rom_cervical_spine",                                    :default => 0
    t.integer  "rom_lumbar_spine",                                      :default => 0
    t.integer  "rom_thoracic_spine",                                    :default => 0
    t.integer  "rom_hip",                                               :default => 0
    t.integer  "rom_shoulder",                                          :default => 0
    t.integer  "rom_elbow",                                             :default => 0
    t.integer  "rom_hand",                                              :default => 0
    t.integer  "rom_knee",                                              :default => 0
    t.integer  "rom_ankle",                                             :default => 0
    t.boolean  "spasm_cervical"
    t.boolean  "spasm_thoracic"
    t.boolean  "spasm_lumbar"
    t.string   "spasm_note"
    t.boolean  "tenderness_cervical"
    t.boolean  "tenderness_thoracic"
    t.boolean  "tenderness_lumbar"
    t.string   "tenderness_note"
    t.boolean  "myofacitis_cervical"
    t.boolean  "myofacitis_thoracic"
    t.boolean  "myofacitis_lumbar"
    t.string   "myofacitis_note"
    t.boolean  "findings_patient_was_given_tens_unit_for_trial_period"
    t.boolean  "findings_tens_unit_is_helping_patient"
    t.boolean  "neck_pain"
    t.string   "neck_pain_side"
    t.integer  "neck_pain_scale"
    t.string   "neck_pain_radiation_side"
    t.boolean  "neck_pain_radiates_to_shoulder"
    t.boolean  "neck_pain_radiates_to_elbow"
    t.boolean  "neck_pain_radiates_to_hand"
    t.boolean  "neck_pain_radiates_to_digit1"
    t.boolean  "neck_pain_radiates_to_digit2"
    t.boolean  "neck_pain_radiates_to_digit3"
    t.boolean  "neck_pain_radiates_to_digit4"
    t.boolean  "neck_pain_radiates_to_digit5"
    t.boolean  "upper_mid_back_pain"
    t.string   "upper_mid_back_pain_side"
    t.integer  "upper_mid_back_pain_scale"
    t.string   "upper_mid_back_pain_radiation_side"
    t.boolean  "low_back_pain"
    t.string   "low_back_pain_side"
    t.integer  "low_back_pain_scale"
    t.string   "low_back_pain_radiation_side"
    t.boolean  "low_back_pain_radiates_to_buttocks"
    t.boolean  "low_back_pain_radiates_to_thighs"
    t.boolean  "low_back_pain_radiates_to_calf"
    t.boolean  "low_back_pain_radiates_to_hips"
    t.boolean  "low_back_pain_radiates_to_knees"
    t.boolean  "low_back_pain_radiates_to_foot"
  end

  create_table "chiropractic_symptom_lists", :force => true do |t|
    t.boolean  "significant_prior_illness_or_injury"
    t.integer  "pain_level_on_vas_resting"
    t.integer  "pain_level_on_vas_activity"
    t.boolean  "neck_pain"
    t.string   "neck_pain_side"
    t.integer  "neck_pain_scale"
    t.string   "neck_pain_radiation_side"
    t.boolean  "neck_pain_radiates_to_shoulder"
    t.boolean  "neck_pain_radiates_to_elbow"
    t.boolean  "neck_pain_radiates_to_hand"
    t.boolean  "neck_pain_radiates_to_digit1"
    t.boolean  "neck_pain_radiates_to_digit2"
    t.boolean  "neck_pain_radiates_to_digit3"
    t.boolean  "neck_pain_radiates_to_digit4"
    t.boolean  "neck_pain_radiates_to_digit5"
    t.boolean  "upper_mid_back_pain"
    t.string   "upper_mid_back_pain_side"
    t.integer  "upper_mid_back_pain_scale"
    t.string   "upper_mid_back_pain_radiation_side"
    t.boolean  "low_back_pain"
    t.string   "low_back_pain_side"
    t.integer  "low_back_pain_scale"
    t.string   "low_back_pain_radiation_side"
    t.boolean  "low_back_pain_radiates_to_buttocks"
    t.boolean  "low_back_pain_radiates_to_thighs"
    t.boolean  "low_back_pain_radiates_to_calf"
    t.boolean  "low_back_pain_radiates_to_hips"
    t.boolean  "low_back_pain_radiates_to_knees"
    t.boolean  "low_back_pain_radiates_to_foot"
    t.boolean  "headaches"
    t.string   "headaches_side"
    t.integer  "headaches_scale"
    t.boolean  "headaches_frontal"
    t.boolean  "headaches_suboccipital"
    t.boolean  "headaches_temporal"
    t.boolean  "headaches_bitemporal"
    t.boolean  "headaches_parietal"
    t.boolean  "numbness"
    t.string   "numbness_side"
    t.integer  "numbness_scale"
    t.boolean  "numbness_upper_extremity_to_elbow"
    t.boolean  "numbness_upper_extremity_to_hand"
    t.boolean  "numbness_lower_extremity_to_knee"
    t.boolean  "numbness_lower_extremity_to_foot"
    t.boolean  "tingling"
    t.string   "tingling_side"
    t.integer  "tingling_scale"
    t.boolean  "tingling_upper_extremity_to_elbow"
    t.boolean  "tingling_upper_extremity_to_hand"
    t.boolean  "tingling_lower_extremity_to_knee"
    t.boolean  "tingling_lower_extremity_to_foot"
    t.text     "other_symptoms"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_examination_id"
  end

  create_table "chiropractic_treatment_plans", :force => true do |t|
    t.boolean  "spine_xray"
    t.boolean  "spine_xray_cervical"
    t.boolean  "spine_xray_thoracic"
    t.boolean  "spine_xray_lumbar"
    t.string   "other_xray"
    t.boolean  "need_xray_reports"
    t.boolean  "need_past_medical_records"
    t.boolean  "spinal_adjustments"
    t.string   "spinal_adjustments_frequency"
    t.boolean  "extremity_adjustments"
    t.string   "extremity_adjustments_frequency"
    t.string   "extremity_adjustment_body_part"
    t.boolean  "recommend_medical_consultation"
    t.string   "recommended_medical_evaluation"
    t.boolean  "re_examine_in_4_weeks"
    t.boolean  "spine_mri"
    t.boolean  "spine_mri_cervical"
    t.boolean  "spine_mri_thoracic"
    t.boolean  "spine_mri_lumbar"
    t.string   "other_mri"
    t.boolean  "spine_ct_scan"
    t.boolean  "spine_ct_scan_cervical"
    t.boolean  "spine_ct_scan_thoracic"
    t.boolean  "spine_ct_scan_lumbar"
    t.string   "other_ct_scan"
    t.boolean  "pending_medical_clearance_for_medications"
    t.string   "taping_frequency"
    t.boolean  "taping_cervical_paraspinal_scm_trapezious_muscles"
    t.boolean  "taping_cervical_disc_bulge_disc_herniation"
    t.boolean  "taping_thoracic_paraspinal_scapular_muscles"
    t.boolean  "taping_low_back_lumbar_paraspinal_lumbar_erectors"
    t.boolean  "taping_lumbar_disc_bulge_disc_herniation"
    t.boolean  "taping_sacroiliac_joint"
    t.text     "other_recommendations"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "chiropractic_examination_id"
    t.boolean  "ultrasound"
    t.boolean  "electric_stimulation"
    t.boolean  "massage"
    t.boolean  "mfr_cervical"
    t.boolean  "mfr_thoracic"
    t.boolean  "mfr_lumbar"
    t.boolean  "mechanical_traction"
    t.string   "other_therapeutic_modality"
    t.boolean  "infrared"
    t.boolean  "hot_cold_pack"
    t.boolean  "bio_feedback"
    t.boolean  "self_care_home_mgmt"
    t.boolean  "therapeutic_exercises"
    t.boolean  "therapeutic_functional_activities"
    t.boolean  "extremity_adjustment_shoulder_left"
    t.boolean  "extremity_adjustment_shoulder_right"
    t.boolean  "extremity_adjustment_hip_left"
    t.boolean  "extremity_adjustment_hip_right"
    t.boolean  "extremity_adjustment_pelvis_left"
    t.boolean  "extremity_adjustment_pelvis_right"
  end

  create_table "chiropractic_treatments", :force => true do |t|
    t.text     "patient_states"
    t.date     "treatment_date"
    t.string   "current_step",                :default => "chiropractic_observation_list"
    t.boolean  "completed",                   :default => false
    t.datetime "completed_at"
    t.integer  "completed_by"
    t.boolean  "insurance_claim_filed",       :default => false
    t.datetime "insurance_claim_filed_at"
    t.integer  "insurance_claim_filed_by"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.boolean  "email_sent",                  :default => false
    t.integer  "chiropractic_examination_id"
    t.integer  "client_id"
    t.string   "summary"
  end

  create_table "clients", :force => true do |t|
    t.string   "name"
    t.string   "address_line1"
    t.string   "address_line2"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "phone"
    t.string   "fax"
    t.string   "report_header_file_name"
    t.string   "report_header_content_type"
    t.integer  "report_header_file_size"
    t.datetime "report_header_updated_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.string   "claim_recipient_email",      :default => "trushal@mdmanage.com"
  end

  create_table "delayed_jobs", :force => true do |t|
    t.integer  "priority",   :default => 0
    t.integer  "attempts",   :default => 0
    t.text     "handler"
    t.text     "last_error"
    t.datetime "run_at"
    t.datetime "locked_at"
    t.datetime "failed_at"
    t.string   "locked_by"
    t.string   "queue"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "delayed_jobs", ["priority", "run_at"], :name => "delayed_jobs_priority"

  create_table "insurance_companies", :force => true do |t|
    t.string   "name"
    t.string   "address_line1"
    t.string   "address_line2"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "phone"
    t.string   "fax"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
  end

  create_table "patients", :force => true do |t|
    t.string   "first_name"
    t.string   "last_name"
    t.date     "date_of_birth"
    t.string   "social_security_number"
    t.string   "gender"
    t.string   "handed"
    t.string   "occupation"
    t.string   "cell_phone"
    t.string   "height_feet_component"
    t.string   "height_inches_component"
    t.string   "weight"
    t.boolean  "ignore_re_examination_reminders",               :default => false
    t.string   "primary_insurance_claim_number"
    t.string   "primary_insurance_policy_number"
    t.integer  "primary_insurance_company_id"
    t.string   "secondary_insurance_claim_number"
    t.string   "secondary_insurance_policy_number"
    t.integer  "secondary_insurance_company_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "client_id"
    t.string   "street_address"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "home_phone"
    t.string   "work_phone"
    t.string   "email"
    t.string   "emergency_contact_name"
    t.string   "emergency_contact_phone"
    t.string   "emergency_contact_relationship"
    t.string   "legal_representative_name"
    t.string   "legal_representative_street_address"
    t.string   "legal_representative_city"
    t.string   "legal_representative_state"
    t.string   "legal_representative_zip"
    t.string   "legal_representative_phone"
    t.string   "legal_representative_fax"
    t.string   "guarantor_name"
    t.string   "guarantor_ssn"
    t.date     "guarantor_date_of_birth"
    t.string   "guarantor_street_address"
    t.string   "guarantor_city"
    t.string   "guarantor_state"
    t.string   "guarantor_zip"
    t.string   "guarantor_phone"
    t.string   "guarantor_fax"
    t.string   "guarantor_email"
    t.string   "primary_insurance_subscribers_name"
    t.date     "primary_insurance_subscribers_date_of_birth"
    t.string   "primary_insurance_subscribers_relationship"
    t.string   "secondary_insurance_subscribers_name"
    t.date     "secondary_insurance_subscribers_date_of_birth"
    t.string   "secondary_insurance_subscribers_relationship"
  end

  create_table "roles", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.string   "password_digest"
    t.string   "password_reset_token"
    t.datetime "password_reset_sent_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "deleted_at"
    t.integer  "role_id"
    t.integer  "client_id"
    t.string   "digital_signature_file_name"
    t.string   "digital_signature_content_type"
    t.integer  "digital_signature_file_size"
    t.datetime "digital_signature_updated_at"
  end

end
