class AddFieldsToChiropracticInvestigationList < ActiveRecord::Migration
  def change
    add_column :chiropractic_investigation_lists, :show_cervical_comp, :boolean
    add_column :chiropractic_investigation_lists, :show_distraction, :boolean
    add_column :chiropractic_investigation_lists, :show_shoulder_dep, :boolean
    add_column :chiropractic_investigation_lists, :show_soto_hall, :boolean
    add_column :chiropractic_investigation_lists, :show_slr, :boolean
    add_column :chiropractic_investigation_lists, :show_braggard, :boolean
    add_column :chiropractic_investigation_lists, :show_kemps, :boolean
    add_column :chiropractic_investigation_lists, :show_valsalva, :boolean
    add_column :chiropractic_investigation_lists, :show_nachlas, :boolean
    add_column :chiropractic_investigation_lists, :show_yeomans, :boolean
    add_column :chiropractic_investigation_lists, :show_fabere_patrick, :boolean
    add_column :chiropractic_investigation_lists, :show_elys, :boolean
    add_column :chiropractic_investigation_lists, :show_georges, :boolean
    add_column :chiropractic_investigation_lists, :show_squat, :boolean
    add_column :chiropractic_investigation_lists, :show_spurlings, :boolean
    add_column :chiropractic_investigation_lists, :show_supraspinatus, :boolean
    add_column :chiropractic_investigation_lists, :show_minors_sign, :boolean
    add_column :chiropractic_investigation_lists, :show_trendelenberg, :boolean
    add_column :chiropractic_investigation_lists, :show_jackson, :boolean
    add_column :chiropractic_investigation_lists, :srom_flex_right_exam, :string
    add_column :chiropractic_investigation_lists, :srom_flex_left_exam, :string
    add_column :chiropractic_investigation_lists, :srom_flex_pain, :boolean
    add_column :chiropractic_investigation_lists, :srom_flex_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :srom_ext_right_exam, :string
    add_column :chiropractic_investigation_lists, :srom_ext_left_exam, :string
    add_column :chiropractic_investigation_lists, :srom_ext_pain, :boolean
    add_column :chiropractic_investigation_lists, :srom_ext_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :srom_int_rot_right_exam, :string
    add_column :chiropractic_investigation_lists, :srom_int_rot_left_exam, :string
    add_column :chiropractic_investigation_lists, :srom_int_rot_pain, :boolean
    add_column :chiropractic_investigation_lists, :srom_int_rot_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :srom_ext_rot_right_exam, :string
    add_column :chiropractic_investigation_lists, :srom_ext_rot_left_exam, :string
    add_column :chiropractic_investigation_lists, :srom_ext_rot_pain, :boolean
    add_column :chiropractic_investigation_lists, :srom_ext_rot_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :srom_adduction_right_exam, :string
    add_column :chiropractic_investigation_lists, :srom_adduction_left_exam, :string
    add_column :chiropractic_investigation_lists, :srom_adduction_pain, :boolean
    add_column :chiropractic_investigation_lists, :srom_adduction_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :srom_abduction_right_exam, :string
    add_column :chiropractic_investigation_lists, :srom_abduction_left_exam, :string
    add_column :chiropractic_investigation_lists, :srom_abduction_pain, :boolean
    add_column :chiropractic_investigation_lists, :srom_abduction_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :hrom_flex_right_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_flex_left_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_flex_pain, :boolean
    add_column :chiropractic_investigation_lists, :hrom_flex_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :hrom_ext_right_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_ext_left_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_ext_pain, :boolean
    add_column :chiropractic_investigation_lists, :hrom_ext_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :hrom_int_rot_right_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_int_rot_left_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_int_rot_pain, :boolean
    add_column :chiropractic_investigation_lists, :hrom_int_rot_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :hrom_ext_rot_right_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_ext_rot_left_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_ext_rot_pain, :boolean
    add_column :chiropractic_investigation_lists, :hrom_ext_rot_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :hrom_adduction_right_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_adduction_left_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_adduction_pain, :boolean
    add_column :chiropractic_investigation_lists, :hrom_adduction_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :hrom_abduction_right_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_abduction_left_exam, :string
    add_column :chiropractic_investigation_lists, :hrom_abduction_pain, :boolean
    add_column :chiropractic_investigation_lists, :hrom_abduction_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :krom_flex_right_exam, :string
    add_column :chiropractic_investigation_lists, :krom_flex_left_exam, :string
    add_column :chiropractic_investigation_lists, :krom_flex_pain, :boolean
    add_column :chiropractic_investigation_lists, :krom_flex_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :krom_ext_right_exam, :string
    add_column :chiropractic_investigation_lists, :krom_ext_left_exam, :string
    add_column :chiropractic_investigation_lists, :krom_ext_pain, :boolean
    add_column :chiropractic_investigation_lists, :krom_ext_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :krom_int_rot_right_exam, :string
    add_column :chiropractic_investigation_lists, :krom_int_rot_left_exam, :string
    add_column :chiropractic_investigation_lists, :krom_int_rot_pain, :boolean
    add_column :chiropractic_investigation_lists, :krom_int_rot_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :krom_ext_rot_right_exam, :string
    add_column :chiropractic_investigation_lists, :krom_ext_rot_left_exam, :string
    add_column :chiropractic_investigation_lists, :krom_ext_rot_pain, :boolean
    add_column :chiropractic_investigation_lists, :krom_ext_rot_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :krom_adduction_right_exam, :string
    add_column :chiropractic_investigation_lists, :krom_adduction_left_exam, :string
    add_column :chiropractic_investigation_lists, :krom_adduction_pain, :boolean
    add_column :chiropractic_investigation_lists, :krom_adduction_discomfort, :boolean
    add_column :chiropractic_investigation_lists, :krom_abduction_right_exam, :string
    add_column :chiropractic_investigation_lists, :krom_abduction_left_exam, :string
    add_column :chiropractic_investigation_lists, :krom_abduction_pain, :boolean
    add_column :chiropractic_investigation_lists, :krom_abduction_discomfort, :boolean
  end
end
